### ISSUE TITLE
Prohibit Numeric Domains

### ISSUE THREAD

**Issue by indolering** [ifa-wg/proposals#11]
Historically, valid domains were defined as valid hostnames per [RFC-1035](http://tools.ietf.org/html/rfc1035),

> They must start with a letter, end with a letter or digit, and have as interior characters only letters, digits, and hyphen.  There are also some restrictions on the length.  Labels must be 63 characters or less.

@hlandau believes we should allow domains that begin with an number (such as `37signals.bit`) but prohibit purely numeric domains (`1.bit`).  I do not care for the additional complexity and it could allow for interesting hacks, but I think future TLDs may want to support this functionality.

_Note that RFC-1035 itself does not equate domain names as valid hostnames and each TLD has it's own rules._

**Comment by hlandau** [comment]
Numeric domains are now prohibited. Closing.
